# Generated by Django 4.1.4 on 2023-01-05 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jardinier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jardin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='jardin/%y/%m/%d/')),
                ('num', models.CharField(max_length=40)),
                ('nom', models.CharField(max_length=40)),
                ('ville', models.CharField(max_length=40)),
                ('adresse', models.CharField(max_length=40)),
                ('superficier', models.IntegerField()),
                ('jardinier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Jardinier.jardinier')),
            ],
        ),
    ]
